Start working on blogpost about UFRN Nextflow graduate course
nextflow-io/website pull request #127
Opened 2023-07-20 03:12 UTC by mribeirodantas

2023-07-20 11:14 UTC, ewels approved these changes

2023-07-20 11:15 UTC, ewels requested changes
Needs a social share image before publishing

2023-07-20 11:15 UTC, ewels commented on content/blog/2023/nextflow-goes-to-university.md
> +image=img/to-be-decided.jpg
Needs this 😊

2023-07-20 11:15 UTC, ewels commented on content/blog/2023/nextflow-goes-to-university.md
> +description=Helpful tips for troubleshooting out-of-memory errors in containerized execution environments.
Needs updating

2023-07-20 11:58 UTC, mribeirodantas commented on content/blog/2023/nextflow-goes-to-university.md
> +image=img/to-be-decided.jpg
Yup, I left this for last haha

2023-07-20 11:59 UTC, mribeirodantas commented on content/blog/2023/nextflow-goes-to-university.md
> +description=Helpful tips for troubleshooting out-of-memory errors in containerized execution environments.
This I missed indeed 🤣

2023-07-23 18:07 UTC, ewels commented on content/blog/2023/nextflow-goes-to-university.md
> +description=Seqera partnership with universities allows students to learn Nextflow and get credits for that!
```suggestion
description=Seqera partnership with universities to help students to learn Nextflow
```

2023-07-23 18:07 UTC, ewels approved these changes

2023-07-23 18:08 UTC, ewels commented on content/blog/2023/nextflow-goes-to-university.md
> +date=2023-07-34
```suggestion
date=2023-07-24
```

2023-07-23 22:56 UTC, mribeirodantas commented on content/blog/2023/nextflow-goes-to-university.md
> +date=2023-07-34
Oooops thanks 😅

2023-07-23 22:56 UTC, merged