Draft: Ambassadors page
nextflow-io/website pull request #138
Opened 2023-09-25 11:01 UTC by ewels

TODO
- [x] Phil wants to slightly enlarge social media icons at the bottom fo the cards
- [ ] Also to add some classes to the cards content (flex, ...)

2023-09-25 11:06 UTC, christopher-hakkaart requested changes
A line of text is in the wrong place?

2023-09-25 11:06 UTC, christopher-hakkaart commented on content/ambassadors.html
> +<p>Oh, and did we mention that there's exclusive swag?</p>
```suggestion
```

2023-09-25 11:06 UTC, christopher-hakkaart commented on content/ambassadors.html
> +        <p>Receive a certificate for your work and appear on the ambassador page of our website.</p>
```suggestion
        <p>Receive a certificate for your work and appear on the ambassador page of our website. Oh, and did we mention that there's exclusive swag?</p>
```

2023-09-25 11:10 UTC, ewels commented
> A line of text is in the wrong place?

That's how it was in the google doc 🤷🏻‍♂️  But I agree, it's better how you had it. Updated.

2023-09-25 11:20 UTC, ewels commented
Hopefully will have some design love before launch, but ready to go now in any case.

2023-09-25 11:21 UTC, christopher-hakkaart approved these changes
🤠

2023-09-27 12:46 UTC, ewels commented
⚠️  Updates on google docs, don't merge until applied here.

2023-10-13 10:33 UTC, ewels commented on content/ambassadors.html
> +<p style="text-align:center; margin: 3rem 0;"><a href="https://seqera.typeform.com/to/CJpqNIks" target="_blank" class="btn btn-color btn-xxl">Register now</a>
```suggestion
<p style="text-align:center; margin: 3rem 0;"><a href="https://seqera.typeform.com/ambassadors" target="_blank" class="btn btn-color btn-xxl">Register now</a>
```

2023-10-18 10:11 UTC, ewels commented on content/ambassadors.html
> +    <a href="/our_ambassadors.html" target="_blank" class="btn btn-color btn-xxl">Check our ambassadors here!</a>
```suggestion
</p>
<p style="text-align:center;">
    <a href="/our_ambassadors.html" class="btn btn-color btn-xxl">Check our ambassadors here!</a>
```

2023-10-18 10:56 UTC, merged