Podcasts rebranding
nextflow-io/website pull request #80
Opened 2022-12-05 11:24 UTC by ewels

* Add new podcast logo to the top of the page
* Update podcast cover art for previous episodes

2022-12-05 11:55 UTC, ewels commented on templates/podcastsindex.ftl
> +        </div>
```suggestion
        <div class="row">
          <div class="col-sm-4">
            <img src="/img/podcast_logo_horiz.svg" style="width:100%;">
          </div>
          <div class="col-sm-8">
            <h4 class='text-muted' style="margin-top: 7rem;">Talking about news in the Nextflow ecosytem and speaking with pioneers in the field.</h4>
          </div>
        </div>
```

2022-12-05 20:24 UTC, mribeirodantas requested changes
Cedric's episode image has an incorrect name below his avatar picture. Everything else is great!

2022-12-05 20:29 UTC, mribeirodantas approved these changes

2022-12-05 20:46 UTC, mribeirodantas commented
I think it's good to merge. What do you think, @pditommaso ?

2022-12-06 09:26 UTC, pditommaso commented
Wonder in the nav bar should be "Podcast" instead of "Podcasts" as it's "Blog" not Blogs" ?

2022-12-06 12:09 UTC, ewels commented
> Wonder in the nav bar should be "Podcast" instead of "Podcasts" as it's "Blog" not Blogs" ?

Fine by me, I'll change it 👍🏻 

Note that the URL is `podcasts.html` but specific episodes are singular (eg. `podcast/2022/ep5_evan_floden.html`). This is because I couldn't figure out how to do an archive page for a custom post type any other way. But I don't think that anyone will notice or care about that, the nav bar is more important.

2022-12-07 11:15 UTC, pditommaso commented
It was fast!

2022-12-07 11:33 UTC, pditommaso commented
Great!

2022-12-07 11:33 UTC, merged

2022-12-07 11:33 UTC, ewels commented
> It was fast!

Thanks to Lilia! Figma reusable components FTW - change in one place and all the graphics automatically update ✨